blog/urls.py
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^blog/$', views.post_list, name='blog'),
    url(r'^blog/(?P<post_id>\d+)/$', views.post_detail,
        name='post-detail'),
    url(r'^blog/voteup/(?P<post_id>\d+)/$', views.post_voteup,
        name='voteup'),
    url(r'^blog/votedown/(?P<post_id>\d+)/$', views.post_votedown,
        name='votedown'),
]

spss_online/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from paypal.standard.ipn import urls as paypal_urls
from paypal_store import views as paypal_views
from home import views
from accounts import views as accounts_views
from products import views as product_views
from contact import views as contact_views


urlpatterns = [

    url(r'^admin/', admin.site.urls),

    # Menu
    url(r'^$', views.get_index, name='index'),
    url(r'^register/$', accounts_views.register, name='register'),
    url(r'^profile/$', accounts_views.profile, name='profile'),
    url(r'^login/$', accounts_views.login, name='login'),
    url(r'^logout/$', accounts_views.logout, name='logout'),
    url(r'^products/$', product_views.all_products, name='products'),
    url(r'^contact/$', contact_views.get_contact, name='contact'),

    # Flatpages
    url(r'^pages/', include('django.contrib.flatpages.urls'),
        name='flatpages'),

    # Paypal
    url(r'^a-very-hard-to-guess-url/', include(paypal_urls)),
    url(r'^paypal-return', paypal_views.paypal_return),
    url(r'^paypal-cancel', paypal_views.paypal_cancel),

    # Blog
    url(r'', include('blog.urls')),

    # Tickets
    url(r'', include('tickets.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(url(r'^debug/', include(debug_toolbar.urls)))
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

tickets/urls.py
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^tickets/$', views.tickets_list, name='tickets-list'),
    url(r'^tickets/(?P<ticket_id>\d+)/$', views.ticket_detail,
        name='ticket-detail'),
    url(r'^new_ticket/$', views.new_ticket, name='new-ticket'),
    url(r'^new_comment/(?P<ticket_id>\d+)/$', views.new_comment,
        name='new-comment'),
    url(r'^close_ticket/(?P<ticket_id>\d+)/$', views.close_ticket,
        name='close-ticket'),
    url(r'^reopen_ticket/(?P<ticket_id>\d+)/$', views.reopen_ticket,
        name='reopen-ticket'),
    url(r'^comment/delete/(?P<ticket_id>\d+)/(?P<comment_id>\d+)/$',
        views.delete_comment, name='delete-comment'),
]

tickets/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone
from tinymce.models import HTMLField
from django.conf import settings


class Ticket(models.Model):
    """
    Tickets are support cases that active customers can log to get help.
    Each ticket contains its own fields and is associated to an user and
    a particular product which customer license
    has to be active at the time of the creation of the ticket.
    The owner of the ticket needs to be a customer in order for the
    customer to see it in the "My Tickets" section.
    Tickets can be opened on the site or from the admin panel.
    """
    statuses = (
        ('NEW', 'New'),
        ('PCR', 'Pending Customer Response'),
        ('PER', 'Pending easySPSS Response'),
        ('CLS', 'Closed'),
    )

    reasons = (
        ('DWL', 'Download Issue'),
        ('INS', 'Installation/Licensing Issue'),
        ('SWI', 'Software Issue'),
        ('OTH', 'Other'),
    )

    subject = models.CharField(max_length=255)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='tickets')
    status = models.CharField(max_length=50, choices=statuses,
                              default='NEW')
    reason = models.CharField(max_length=50, choices=reasons,
                              default='OTH')
    product = models.ForeignKey('products.Product',
                                related_name='tickets')
    opened_date = models.DateTimeField(default=timezone.now)
    closed_date = models.DateTimeField(blank=True, null=True)

    def __unicode__(self):
        return '%s - %s' % (self.subject, self.user.email)


class Comment(models.Model):
    """
    Comments are the way users and staff communicate in tickets.
    Each ticket must contain at least one comment.
    Each comment is associated to a ticket and a user.
    If a ticket is created in the admin panel, a comment associated
    to it should be created immediately after.
    Comments can be created on the site or from the admin panel.
    """
    ticket = models.ForeignKey(Ticket, related_name='comments')
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='comments')
    comment = HTMLField()
    created_date = models.DateTimeField(default=timezone.now)

    def __unicode__(self):
        return '%s - ticket:%s - %s' % (self.pk, self.ticket_id, self.user)

tickets/forms.py
from django import forms
from .models import Ticket, Comment
from products.models import Purchase


class TicketForm(forms.ModelForm):
    """
    Form to create new tickets
    The field product only shows the products related to
    purchases whose license are active
    """

    product = forms.ModelChoiceField(queryset=Purchase.objects.all())

    def __init__(self, *args, **kwargs):
        super(TicketForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Ticket
        fields = ['subject', 'reason', 'product']


class CommentForm(forms.ModelForm):
    """ Form to create new comments """

    class Meta:
        model = Comment
        fields = ['comment']

tickets/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.template.context_processors import csrf
from django.utils import timezone
from .forms import TicketForm, CommentForm
from tickets.models import Comment, Ticket
from products.models import Purchase, Product
from django.core.mail import send_mail

""" All views rendering templates are for authenticated users only"""


@login_required(login_url='/login/')
def tickets_list(request):
    """
    Show tickets page
    Return a list with the relevant tickets for the user
    authenticated to the ticket_list template.
    - If the user is staff: return all tickets
    - If the user is customer/registered: return its own tickets
    """

    user = request.user
    if user.is_staff:
        # Get list of all tickets for staff user
        tickets = Ticket.objects.all().order_by('-opened_date')
        comments = Comment.objects.all()
        for ticket in tickets:
            if ticket.comments.count() > 1 and ticket.status != 'CLS':
                update_pending_status(request, ticket)
    else:
        # Get list of tickets for the logged user
        tickets = Ticket.objects.filter(user_id=user.id)\
            .order_by('-opened_date')
        comments = Comment.objects.filter(user_id=user.id)

    args = {'tickets': tickets, 'comments': comments}
    return render(request, 'tickets/tickets_list.html', args)


@login_required(login_url='/login/')
def ticket_detail(request, ticket_id):
    """
    Show ticket detail page.
    Get the ticket with the id passed and return a the details
    and comments associated with that ticket
    to the ticket_detail template
    """

    ticket = get_object_or_404(Ticket, pk=ticket_id)
    comments = Comment.objects.filter(ticket_id=ticket_id)\
        .order_by('created_date')
    if comments.count() > 1 and ticket.status != 'CLS':
        update_pending_status(request, ticket)

    args = {'ticket': ticket, 'comments': comments}
    args.update(csrf(request))
    return render(request, 'tickets/ticket_detail.html', args)


@login_required(login_url='/login/')
def new_ticket(request):
    """
    Register a new ticket and comment.
    Show the new ticket and new comment forms and save the
    objects when both forms are validated.
    Tickets are associated to active product licenses when created.
    Only active licenses are showed in the dropdown.
    """

    if request.method == 'POST':
        ticket_form = TicketForm(request.POST)
        user_purchases = Purchase.objects.filter(user=request.user)
        active_purchases = Purchase.objects.filter(license_end__gte=timezone.now())
        purchases = user_purchases & active_purchases
        active_products = [purchase.product_id for purchase in purchases]
        ticket_form.fields['product'].queryset = Product.objects\
            .filter(pk__in=active_products)
        comment_form = CommentForm(request.POST)

        if ticket_form.is_valid() and comment_form.is_valid():
            ticket = ticket_form.save(False)
            ticket.user = request.user
            ticket.save()

            comment = comment_form.save(False)
            comment.ticket = ticket
            comment.user = request.user
            comment.save()

            messages.success(request, "Your ticket has been logged.\n"
                                      "We will send you an email"
                                      "when you get a new response.",
                             extra_tags='alert alert-success')
            return redirect(reverse('ticket-detail', args={ticket.pk}))

    else:
        ticket_form = TicketForm()
        # Set up the list of products so it only shows
        # the active products for the user
        user_purchases = Purchase.objects.filter(user=request.user)
        active_purchases = Purchase.objects\
            .filter(license_end__gte=timezone.now())
        purchases = user_purchases & active_purchases
        active_products = [purchase.product_id for purchase in purchases]
        ticket_form.fields['product'].queryset = Product.objects\
            .filter(pk__in=active_products)

        comment_form = CommentForm(request.POST)

    args = {'ticket_form': ticket_form, 'comment_form': comment_form}
    args.update(csrf(request))

    return render(request, 'tickets/ticket_form.html', args)


@login_required(login_url='/login/')
def new_comment(request, ticket_id):
    """
    Register a new comment in a given ticket.
    Get the ticket associated with the id passed,
    show new comment form and save the comment when the form is validated
    """

    ticket = get_object_or_404(Ticket, pk=ticket_id)
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(False)
            comment.ticket = ticket
            comment.user = request.user
            comment.save()
            messages.success(request, "Your comment has been logged",
                             extra_tags='alert alert-success')
            if comment.user.is_staff:
                send_email_comment(request, ticket, comment)

            return redirect(reverse('ticket-detail', args={ticket.pk}))
    else:
        comment_form = CommentForm(request.POST)
        args = {
            'comment_form': comment_form,
            'form_action': reverse('new-comment', args=[ticket_id]),
            'button_text': 'Add Comment',
            'ticket_id': ticket_id
        }

        args.update(csrf(request))
        return render(request, 'tickets/comment_form.html', args)


def update_pending_status(request, ticket):
    """
    Function to update status depending on last commented user.
    Get the last comment of the ticket and update the
    ticket status in concordance:
     Pending Customer Response (PCR) if the last comment was from a staff user
     and Pending easySPSS Reponse (PER) if the last comment was from a customer
     """

    last_comment = ticket.comments.all().order_by('created_date').last()
    if last_comment.user.is_staff:
        ticket.status = "PCR"
    else:
        ticket.status = "PER"
    ticket.save()


def close_ticket(request, ticket_id):
    """
    Close an open ticket.
    Change the ticket status to closed and return to ticket detail page
    """

    ticket = get_object_or_404(Ticket, pk=ticket_id)
    ticket.status = "CLS"
    ticket.closed_date = timezone.now()
    ticket.save()
    messages.success(request, "The ticket has been closed",
                     extra_tags='alert alert-success')
    return redirect(reverse('ticket-detail', args={ticket_id}))


def reopen_ticket(request, ticket_id):
    """
    Reopen a closed ticket
    Change the ticket status depending on the last comment
    and return to ticket detail page
    """

    ticket = get_object_or_404(Ticket, pk=ticket_id)
    update_pending_status(request, ticket)
    ticket.closed_date = None
    ticket.save()
    messages.success(request, "The ticket has been re-opened",
                     extra_tags='alert alert-success')
    return redirect(reverse('ticket-detail', args={ticket_id}))


def delete_comment(request, ticket_id, comment_id):
    """
    Delete a comment.
    Get the comment, delete it and return to ticket detail page
    """

    comment = get_object_or_404(Comment, pk=comment_id)
    comment.delete()
    messages.success(request, "The comment was deleted!",
                     extra_tags='alert alert-success')

    return redirect(reverse('ticket-detail', args={ticket_id}))


def send_email_comment(request, ticket, comment):
    """
    Send email to user.
    Send a notification email to the user when a staff member
    adds a new comment.
    """
    subject = "New comment in ticket: %s" % ticket.subject
    message = "Hi %s,\n\n" \
              "A new comment has been added to ticket '%s'.\n\n" \
              "You can see the details in 'My Tickets':" \
              "https://spss-online.herokuapp.com/tickets/%s\n\n"\
              "Kind regards,\n easySPSS Team"\
              % (comment.user.first_name, ticket.subject, ticket.id)

    from_email = "easyspssweb@gmail.com"
    send_mail(subject, message, from_email, [ticket.user.email])

templates/tickets/comment_form.html
{% extends 'base.html' %}
{% load bootstrap_tags %}
{% load staticfiles %}

{% block head_js %}
    <!-- load tinymce for comment field -->
    <script src="{% static 'js/tinymce/tinymce.min.js' %}"></script>
    <script type="text/javascript">
        tinyMCE.init({ mode: "textareas", theme: "modern", plugins: "paste" });
    </script>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <form method="post" action="{{ form_action }}">
                {% csrf_token %}
                {{ comment_form | as_bootstrap }}
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Add Comment</button>
                    <a href="{% url 'ticket-detail' ticket_id %}" class="btn btn-default">Cancel</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/tickets/ticket_detail.html
{% extends "base.html" %}
{% load ticket_extras %}

{% block content %}
    <!-- header -->
    {% if user.is_authenticated %}
        <div class="row">
            <!-- Ticket status and show warning message for inactive customers -->
            <div class="col-md-6">
                {% if not user.is_customer and not user.is_staff %}
                    <p id="ticket-inactive-msg" class="alert alert-warning">Only Active Customers can open and update
                        tickets. If your account is inactive but you need help with an open ticket please
                        <a href="{% url 'contact' %}">contact us</a>.</p>
                {% endif %}
                <h3 id="ticket-status"
                    class="{% if ticket.status == "CLS" %}text-danger{% else %} text-success{% endif %} ">
                        Status: {{ ticket.get_status_display }}</h3>
             </div>
            <div class="col-md-6">
                {% if not user.is_staff %}
                            <a  id="ticket-new-ticket"
                                href="{% url 'new-ticket' %}" class="btn btn-default btn-tickets">Open New Ticket</a>&emsp;
                        {% endif %}
                <a href="{% url 'tickets-list' %}" class="btn btn-default btn-tickets">Back to My Tickets</a>

            </div>
        </div>
        <!-- end header -->

        <div class="row">
            <!-- Buttons to update tickets -->
                {% if user.is_customer or user.is_staff  %}
                    <div class="col-md-6">
                    {% if ticket.status != "CLS" %}
                        <a id="ticket-add-comment"
                           href="{% url 'new-comment' ticket.id %}" class="btn btn-primary btn-tickets">Add Comment</a>&emsp;
                        <a  id="ticket-close-ticket"
                            href="{% url 'close-ticket' ticket.id %}" class="btn btn-danger btn-tickets">Close Ticket</a>
                    {% else %}
                        <a  id="ticket-reopen-ticket"
                            href="{% url 'reopen-ticket' ticket.id %}" class="btn btn-warning btn-tickets">Reopen Ticket</a>
                    {% endif %}
                    </div>

                {% endif %}
            </div>
        </div>

        <!-- ticket header -->
        <div class="row">
            <!-- Ticket subject -->
            <div class="col-md-9">
                <h2>Ticket: {{ ticket.subject }}</h2>
            </div>
        </div>
        <div class="row">
            <!-- ticket details -->
            <div class="col-md-9">
                <p><b>Product:</b> {{ ticket.product }}</p>
                <p><b>Reason: </b>{{ ticket.get_reason_display }}</p>
                <p><b>Created date:</b> {{ ticket.opened_date }}
                {% if ticket.closed_date != None %}
                    | <b>Closed date:</b> {{ ticket.closed_date }}
                {% endif %}
                </p>
                <p>Last commented by {% last_comment_user ticket %} {% last_comment_date ticket %}</p>
                <br><br>
                <h4>Comments</h4>
                <table class="table"><tbody>
                    {% for comment in comments   %}
                        <tr><td>
                            <b>{{ comment.user.first_name }} {{ comment.user.last_name }} |
                                {% comment_date_humanized comment%}</b>
                            <br><br>{% autoescape off %}
                            {{ comment.comment }}
                            {% endautoescape %}
                            <!-- Staff can delete comments if ticket is not closed -->
                            {% if ticket.status != "CLS" and user.is_staff %}
                                {% if ticket.comments.count > 1 %}
                                   <div class="pull-right">
                                        <a id="ticket-delete-comment-{{ comment.id }}"
                                           href="{% url 'delete-comment' ticket.id comment.id %}">
                                            <i class="fa fa-trash-o"></i></a>
                                    </div>
                                {% endif %}
                            {% endif %}
                            <div class="spacer">&nbsp;</div>
                        </td></tr>
                    {% endfor %}
                </tbody></table>
            </div>
            <!-- end ticket details -->
        </div>
    {% endif %}
{% endblock %}

templates/tickets/ticket_form.html
{% extends 'base.html' %}
{% load bootstrap_tags %}
{% load staticfiles %}

{% block head_js %}
    <!-- load tinymce for comment field -->
    <script src="{% static 'js/tinymce/tinymce.min.js' %}"></script>
    <script>
        tinyMCE.init({mode: "textareas", theme: 'modern', plugins: 'paste'})
    </script>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <form method="post" action="{% url 'new-ticket' %}">
                {% csrf_token %}
                {{ ticket_form | as_bootstrap }}
                <hr>
                {{ comment_form | as_bootstrap }}
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Open Ticket</button>
                    <a href="{% url 'tickets-list'%}" class="btn btn-default">Cancel</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/tickets/ticketdetail.html
{% extends "base.html" %}
{% load ticket_extras %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            {% if user.is_authenticated %}
                <h3 class=" {% if ticket.status == "CLS" %}text-danger{% else %} text-success{% endif %} ">
                        Status: {{ ticket.get_status_display }}</h3>
        </div>
        <div class="col-md-6"><a href="{% url 'tickets' %}" class="btn btn-default">Back to My Tickets</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
                {% if user.is_customer or user.is_staff  %}
                    {% if ticket.status != "CLS" %}
                        <a href="{% url 'new-comment' ticket.id %}" class="btn btn-default">Add Comment</a> &emsp;
                            <a href="{% url 'close-ticket' ticket.id %}" class="btn btn-danger">Close Ticket</a>
                    {% else %}
                        <a href="{% url 'reopen-ticket' ticket.id %}" class="btn btn-danger">Reopen Ticket</a>
                    {% endif %}
                    </div><div class="col-md-6">
                    <a href="{% url 'new-ticket' %}" class="btn btn-primary">Open New Ticket</a>
                {% else %}
                    </div><div class="col-md-6">
                    <p><a href="{% url 'new-ticket' %}" class="btn btn-primary disabled ">Open New Ticket </a>
                        Only active customers can open cases</p>
                {% endif %}

            {% else %}
                <p>You are not logged in</p>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <h2>Ticket: {{ ticket.subject }}</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <p><b>Product:</b> {{ ticket.product }}</p>
            <p><b>Reason: </b>{{ ticket.reason }}</p>
            <p><b>Created date:</b> {{ ticket.opened_date }}
            {% if ticket.closed_date != None %}
                | <b>Closed date:</b> {{ ticket.closed_date }}
            {% endif %}
            </p>
            <p>Last commented by {% last_comment_user ticket %} on {% last_comment_date ticket %}</p>
            <br><br>
            <h4>Comments</h4>
            <table class="table">
                <tbody>
                {% for comment in comments  %}
                <tr><td>
                    <b>{{ comment.user.first_name }} {{ comment.user.last_name }} | {% comment_date_humanized comment%}</b>
                    <br><br>
                    {{ comment.comment }}
                    <br><br>
                </td></tr>
            {% endfor %}
            </tbody>
            </table>
        </div>
    </div>

{% endblock %}

templates/tickets/tickets.html
{% extends "base.html" %}
{% block content %}
    {% load bootstrap_tags %}
    {% load ticket_extras %}

    <div class="row">
        <div class="col-md-12">
            {% if user.is_authenticated and user.is_customer %} <!-- and is_customer-->
                <p><a href="{% url 'new-ticket' %}" class="btn btn-primary">Open New Ticket</a> </p>
            {% else %}
                <p><a href="{% url 'new-ticket' %}" class="btn btn-primary disabled ">Open New Ticket </a>
                    Only customers with active products can create new tickets</p>
            {% endif %}
            {% if tickets %}
                <section class="ticket">
                    <table class="table ">
                        <thead><tr>
                            <th>Status</th>
                            <th>Prod. Code</th>
                            <th>Subject</th>
                            <th>Opened</th>
                            <th>Closed</th>
                            <th>Comments</th>
                            <th>Last comment</th>

                        </tr></thead>
                        <tbody>
                            {% for ticket in tickets %}
                                <tr>
                                    <td>{{ ticket.get_status_display }}</td>
                                    <td>{{ ticket.product.code }}</td>
                                    <td><a href="{{ ticket.id }}">{{ ticket.subject }}</a></td>
                                    <td>{{ ticket.opened_date | date}}</td>
                                    <td>{% if ticket.closed_date %}
                                        {{ ticket.closed_date }} {% endif %}</td>
                                    <td>{{ ticket.comments.count }}</td>
                                    <td>{% last_comment_user ticket %} | {% last_comment_date ticket %}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </section>
            {% else %}

            <p>No tickets to show.</p>
        {% endif %}
        </div>
    </div>

{% endblock %}

templates/tickets/tickets_list.html
{% extends "base.html" %}
{% load bootstrap_tags %}
{% load ticket_extras %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
        <h1>My Tickets</h1>
            <!-- buttons & alerts -->
            <!-- Staff can't open tickets on the site as it needs to be linked to a customer.  -->
            {% if user.is_customer and not user.is_staff %}
                <p id="open-ticket"><a href="{% url 'new-ticket' %}" class="btn btn-primary">Open New Ticket</a> </p>
                <!-- Non active Customers can't open or edit tickets -->
            {% elif not user.is_staff %}
                <p id="tickets-inactive-msg" class="alert alert-warning">Only Active Customers can open and update
                    tickets. If your account is inactive but you need help with an open ticket please
                    <a href="{% url 'contact' %}">contact us</a>.</p>
            {% endif %}
            <!-- end buttons and alerts -->
            <!-- Tickets table. Some information changes depending on the type of user -->
            {% if tickets %}
                <div class="ticket">
                    <table class="table ">
                        <thead><tr>
                            <th>Status</th>
                            {% if user.is_staff %}
                                <th>Customer</th>
                            {% endif %}
                            <th>Subject</th>
                            <th>Prod. Code</th>
                            <th>Opened</th>
                            <th>Closed</th>
                            <th>Comments</th>
                            <th>Last comment</th>
                        </tr></thead>
                        <tbody>
                            {% for ticket in tickets  %}
                                {% if ticket.comments.count > 0 %}
                                    <tr>
                                     {% if user.is_staff %}
                                        <td id="status-{{ ticket.id }}">{{ ticket.status }}</td>
                                         <td>{{ ticket.user.first_name }} {{ ticket.user.last_name }}</td>
                                     {% else %}
                                        <td>{{ ticket.get_status_display }}</td>
                                     {%  endif %}
                                        <td><a href="{{ ticket.id }}">{{ ticket.subject |truncatewords_html:10 }}</a></td>
                                        <td>{{ ticket.product.code }}</td>
                                        <td>{{ ticket.opened_date | date}}</td>
                                        <td>{% if ticket.closed_date  %}
                                            {{ ticket.closed_date | date}} {% endif %}</td>
                                        <td><span class="badge">{{ ticket.comments.count }}</span></td>
                                        <td>{% last_comment_date ticket %}</td>
                                    </tr>
                                {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <p>No tickets to show.</p>
            {% endif %}
            <!-- end tickets table -->
        </div>
    </div>
{% endblock %}